<script>
require(['prototype'], function(){

//<![CDATA[
    function refreshStats() {
        var message = $('validation_result');

        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            onSuccess: function(response) {
                var result = '<?php echo __('Error during refresh stats.') ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        message.removeClassName('hidden').addClassName('success')
                    } else {
                        message.removeClassName('hidden').addClassName('error')
                    }
                } catch (e) {
                    message.removeClassName('hidden').addClassName('error')
                }
                message.update(result);
            }
        });
    }

    window.refreshStats = refreshStats;
//]]>

});
</script>
<div class="actions actions-refresh-stats">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:refreshStats(); return false;" class="action-refresh-stats" type="button" id="lifetime_sales_config_action">
        <span><?php echo $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>